### PR TITLE
Fix gnome_sdk_version

### PR DESCRIPTION
**Pull request by sonnyp**
See https://matrix.to/#/!owVIjvsVrBaEdelYem:matrix.org/$1683413819550UZWCH:gnome.org?via=libera.chat&via=matrix.org&via=gnome.org

### CODE REVIEW

**Comment by 007AnupamSharma** [comment]
I need your help @sonnyp is there any way of conversation

**Comment by sonnyp** [comment]
This is already fixed in GNOME Builder flathub

See https://github.com/flathub/org.gnome.Builder/pull/41

**Comment by sonnyp** [comment]
see https://gsoc.gnome.org/

**Comment by 007AnupamSharma** [comment]
is it now available to apply??

**Comment by 007AnupamSharma** [comment]
I'm totally in chaos about what i need to do for the next step ... it will be very kind of you to guide me 
so that one day I also got selected .....
it's my Linkedin id : https://www.linkedin.com/in/anupam-sharma-686aa2207 please accept it so that further conservation will be done ... please help me thought you were helping your little brother

**Pull request closed without merging**
